#!/usr/bin/env sh
# TODO: deharcdcode deployment (from both commands)
nixops ssh-for-each -d multi -p 'mkdir -p /var/state /var/glusterfs'

# TODO: Dehardcode machine names
nixops ssh -d multi maszyna0 gluster peer probe maszyna1
nixops ssh -d multi maszyna0 gluster peer probe maszyna2
nixops ssh -d multi maszyna0 gluster volume create state replica 3 maszyna0:/var/glusterfs maszyna1:/var/glusterfs maszyna2:/var/glusterfs force
nixops ssh -d multi maszyna0 gluster volume start state
