#!/usr/bin/env sh
nixops ssh-for-each -p 'mkdir -p /var/state /var/glusterfs'

# TODO: Dehardcode machine names
nixops ssh maszyna0 gluster peer probe maszyna1
nixops ssh maszyna0 gluster peer probe maszyna2
nixops ssh maszyna0 gluster volume create state replica 3 maszyna0:/var/glusterfs maszyna1:/var/glusterfs maszyna2:/var/glusterfs force
nixops ssh maszyna0 gluster volume start state
